In [2]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [1]:
# Import torch
import torch

# Create random tensor of size 3 by 3
your_first_tensor = torch.rand((3, 3))

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

tensor([[0.2088, 0.4819, 0.2507],
        [0.1624, 0.1697, 0.9547],
        [0.3918, 0.3733, 0.6478]])
torch.Size([3, 3])


In [3]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones * identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


- Initialize random tensors x, y and z, each having shape (1000, 1000).
- Multiply x with y, putting the result in tensor q.
- Do an elementwise multiplication of tensor z with tensor q, putting the results in f

In [4]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = x * y

# Multiply elementwise z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(0.1249)


Backpropagation using PyTorch

In [5]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


In [ ]:
# Multiply tensors x and y
q = torch.matmul(x, y)

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

# Introduction to Neural Networks
- the job of the hidden layers is to get good features, while the job of the output layer is to classify those features.

- Look at the matrix of weights, the first dimension should always correspond to the preceding layer, while the second dimension to the following layer. As you can imagine, `h1` contains 20 units. Similarly, we continue for the second hidden layer `h2`, which is the product of the first hidden layer `h1` and the second matrix of weights `w2`. Finally, we get the results of the output_layer, which has 4 classes, by multiplying the second hidden layer `h2` with the third matrix of weights `w3`.
- (=)가중치 행렬을 보면 첫 번째 차원은 항상 이전 레이어와 일치해야 하고 두 번째 차원은 다음 레이어와 일치해야 합니다. 상상할 수 있듯이 `h1`에는 20개의 단위가 있습니다. 유사하게, 첫 번째 히든 레이어 'h1'과 가중치 'w2'의 두 번째 행렬의 곱인 두 번째 히든 레이어 'h2'에 대해 계속 진행합니다. 마지막으로 두 번째 히든 레이어 'h2'와 가중치 'w3'의 세 번째 행렬을 곱하여 4개의 클래스를 가진 output_layer의 결과를 얻습니다.

In [6]:
import torch

input_layer = torch.rand(10)

w1 = torch.rand(10, 20)
w2 = torch.rand(20, 20)
w3 = torch.rand(20, 4)

h1 = torch.matmul(input_layer, w1)
h2 = torch.matmul(h1, w2)
output_layer = torch.matmul(h2, w3)

print(output_layer)

tensor([354.3600, 289.8020, 302.2944, 324.6020])


In [8]:
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(10, 20)
        self.fc2 = nn.Linear(20, 20)
        self.output = nn.Linear(20, 4)
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.output(x)
        return x

In [9]:
'''
You are going to build a neural network in PyTorch, 
using the hard way. Your input will be images of size (28, 28), 
so images containing 784 pixels. Your network will contain an input_layer (provided for you), 
a hidden layer with 200 units, and an output layer with 10 classes. 

The input layer has already been created for you. 
You are going to create the weights, and then do matrix multiplications, getting the results from the network.
'''

# Initialize the weights of the neural network
weight_1 = torch.rand(784, 20)
weight_2 = torch.rand(20, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

RuntimeError: ignored

In [10]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x